### ISSUE TITLE
Supporting other storage solutions

### ISSUE THREAD

**Issue by Arteneko** [furkansenharputlu/f-license#10]
I was wondering if it was possible for this tool to support other storage mechanisms, typically a SQLite/PostgreSQL storage.

**Comment by furkansenharputlu** [comment]
Thanks for opening the issue. Yes, I implemented the storage as interface. So, I have plan to add PostgreSQL implementation as well.

**Comment by Arteneko** [comment]
Thanks for the heads-up, and good luck towards building it!
