### ISSUE TITLE
Add dockerfile

### ISSUE THREAD

**Issue by PNRxA** [furkansenharputlu/f-license#16]
Is it possible to include a dockerfile in this project for easy deployment?

**Comment by furkansenharputlu** [comment]
Thank you! It is a good idea. It will be added soon.

**Comment by furkansenharputlu** [comment]
@PNRxA Here is the dockerfile: https://github.com/furkansenharputlu/f-license/blob/master/Dockerfile

**Comment by PNRxA** [comment]
@furkansenharputlu amazing! Greatly appreciate it
