### ISSUE TITLE
can't go get 

### ISSUE THREAD

**Issue by czyCoder** [furkansenharputlu/f-license#22]
go get github.com/furkansenharputlu/f-license/client
go get github.com/furkansenharputlu/f-license/client: no matching versions for query "upgrade"

**Comment by furkansenharputlu** [comment]
Thanks for reporting this issue! However, I cannot reproduce it. Can you please provide more details and steps?

**Comment by furkansenharputlu** [comment]
Closing this issue for now. If you see the same problem, feel free to open it.
